# Generated by Django 4.2.1 on 2023-09-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
